version: "3.9"
services:
  db:
    image: postgres
    ports:
      - '5433:5433'
    volumes:
       - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password
    command: -p 5433
  web:
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - REDIS_URL_CACHING=redis://redis:6380/0
  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --port 6380
    ports:
      - '6380:6380'
    volumes:
      - 'redis:/data'
volumes:
  redis:
  postgres:
